# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  buildtoSolution: 'PizzaProject1'
  buildtoPath: 'PizzaProject1/PizzaProject1'
  builttoTest: 'PizzaProject1/PizzaProject1.Testing'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
  workingDirectory: '$(pathtoSolution)'

- script: dotnet test
   --configuration $(buildConfiguration)
   --logger trx
   --no-build
   --results-directory $(Build.ArtifactStagingDirectory)/test/
    /p:CollectCoverage=true
    /p:CoverletOutputFormat=opencover
    /p:CoverletOutput='$(Build.ArtifactStagingDirectory)/coverage/'
  workingDirectory: '$(pathtoSolution)'
  displayName: 'dotnet Test'
